# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import nintendo_pb2 as nintendo__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nintendo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NintendoServiceStub(object):
    """Servicio principal de NintendoApi.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateConsole = channel.unary_unary(
                '/nintendo.NintendoService/CreateConsole',
                request_serializer=nintendo__pb2.CreateConsoleRequest.SerializeToString,
                response_deserializer=nintendo__pb2.ConsoleResponse.FromString,
                _registered_method=True)
        self.GetConsoleById = channel.unary_unary(
                '/nintendo.NintendoService/GetConsoleById',
                request_serializer=nintendo__pb2.GetConsoleByIdRequest.SerializeToString,
                response_deserializer=nintendo__pb2.ConsoleResponse.FromString,
                _registered_method=True)
        self.ListConsoles = channel.unary_unary(
                '/nintendo.NintendoService/ListConsoles',
                request_serializer=nintendo__pb2.ListConsolesRequest.SerializeToString,
                response_deserializer=nintendo__pb2.ListConsolesResponse.FromString,
                _registered_method=True)
        self.UpdateConsole = channel.unary_unary(
                '/nintendo.NintendoService/UpdateConsole',
                request_serializer=nintendo__pb2.UpdateConsoleRequest.SerializeToString,
                response_deserializer=nintendo__pb2.ConsoleResponse.FromString,
                _registered_method=True)
        self.DeleteConsole = channel.unary_unary(
                '/nintendo.NintendoService/DeleteConsole',
                request_serializer=nintendo__pb2.DeleteConsoleRequest.SerializeToString,
                response_deserializer=nintendo__pb2.DeleteConsoleResponse.FromString,
                _registered_method=True)


class NintendoServiceServicer(object):
    """Servicio principal de NintendoApi.
    """

    def CreateConsole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConsoleById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConsoles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConsole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteConsole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NintendoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateConsole': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateConsole,
                    request_deserializer=nintendo__pb2.CreateConsoleRequest.FromString,
                    response_serializer=nintendo__pb2.ConsoleResponse.SerializeToString,
            ),
            'GetConsoleById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConsoleById,
                    request_deserializer=nintendo__pb2.GetConsoleByIdRequest.FromString,
                    response_serializer=nintendo__pb2.ConsoleResponse.SerializeToString,
            ),
            'ListConsoles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConsoles,
                    request_deserializer=nintendo__pb2.ListConsolesRequest.FromString,
                    response_serializer=nintendo__pb2.ListConsolesResponse.SerializeToString,
            ),
            'UpdateConsole': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConsole,
                    request_deserializer=nintendo__pb2.UpdateConsoleRequest.FromString,
                    response_serializer=nintendo__pb2.ConsoleResponse.SerializeToString,
            ),
            'DeleteConsole': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteConsole,
                    request_deserializer=nintendo__pb2.DeleteConsoleRequest.FromString,
                    response_serializer=nintendo__pb2.DeleteConsoleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nintendo.NintendoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nintendo.NintendoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NintendoService(object):
    """Servicio principal de NintendoApi.
    """

    @staticmethod
    def CreateConsole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nintendo.NintendoService/CreateConsole',
            nintendo__pb2.CreateConsoleRequest.SerializeToString,
            nintendo__pb2.ConsoleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConsoleById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nintendo.NintendoService/GetConsoleById',
            nintendo__pb2.GetConsoleByIdRequest.SerializeToString,
            nintendo__pb2.ConsoleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListConsoles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nintendo.NintendoService/ListConsoles',
            nintendo__pb2.ListConsolesRequest.SerializeToString,
            nintendo__pb2.ListConsolesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateConsole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nintendo.NintendoService/UpdateConsole',
            nintendo__pb2.UpdateConsoleRequest.SerializeToString,
            nintendo__pb2.ConsoleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteConsole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nintendo.NintendoService/DeleteConsole',
            nintendo__pb2.DeleteConsoleRequest.SerializeToString,
            nintendo__pb2.DeleteConsoleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
