# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nintendo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nintendo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0enintendo.proto\x12\x08nintendo\"\xca\x01\n\x07\x43onsole\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tcode_name\x18\x03 \x01(\t\x12\x12\n\ngeneration\x18\x04 \x01(\x05\x12\x14\n\x0crelease_year\x18\x05 \x01(\x05\x12\x19\n\x11\x64iscontinued_year\x18\x06 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x07 \x01(\t\x12\x0f\n\x07regions\x18\x08 \x03(\t\x12\x10\n\x08portable\x18\t \x01(\x08\x12\x15\n\rsupport_email\x18\n \x01(\t\":\n\x14\x43reateConsoleRequest\x12\"\n\x07\x63onsole\x18\x01 \x01(\x0b\x32\x11.nintendo.Console\"5\n\x0f\x43onsoleResponse\x12\"\n\x07\x63onsole\x18\x01 \x01(\x0b\x32\x11.nintendo.Console\"#\n\x15GetConsoleByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"d\n\x13ListConsolesRequest\x12\x11\n\tpage_size\x18\x01 \x01(\x05\x12\x12\n\npage_token\x18\x02 \x01(\t\x12\x12\n\ngeneration\x18\x03 \x01(\x05\x12\x12\n\nname_query\x18\x04 \x01(\t\"i\n\x14ListConsolesResponse\x12#\n\x08\x63onsoles\x18\x01 \x03(\x0b\x32\x11.nintendo.Console\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0btotal_count\x18\x03 \x01(\x03\"F\n\x14UpdateConsoleRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\"\n\x07\x63onsole\x18\x02 \x01(\x0b\x32\x11.nintendo.Console\"\"\n\x14\x44\x65leteConsoleRequest\x12\n\n\x02id\x18\x01 \x01(\t\"(\n\x15\x44\x65leteConsoleResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x98\x03\n\x0fNintendoService\x12J\n\rCreateConsole\x12\x1e.nintendo.CreateConsoleRequest\x1a\x19.nintendo.ConsoleResponse\x12L\n\x0eGetConsoleById\x12\x1f.nintendo.GetConsoleByIdRequest\x1a\x19.nintendo.ConsoleResponse\x12M\n\x0cListConsoles\x12\x1d.nintendo.ListConsolesRequest\x1a\x1e.nintendo.ListConsolesResponse\x12J\n\rUpdateConsole\x12\x1e.nintendo.UpdateConsoleRequest\x1a\x19.nintendo.ConsoleResponse\x12P\n\rDeleteConsole\x12\x1e.nintendo.DeleteConsoleRequest\x1a\x1f.nintendo.DeleteConsoleResponseB\nZ\x08nintendob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nintendo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\010nintendo'
  _globals['_CONSOLE']._serialized_start=29
  _globals['_CONSOLE']._serialized_end=231
  _globals['_CREATECONSOLEREQUEST']._serialized_start=233
  _globals['_CREATECONSOLEREQUEST']._serialized_end=291
  _globals['_CONSOLERESPONSE']._serialized_start=293
  _globals['_CONSOLERESPONSE']._serialized_end=346
  _globals['_GETCONSOLEBYIDREQUEST']._serialized_start=348
  _globals['_GETCONSOLEBYIDREQUEST']._serialized_end=383
  _globals['_LISTCONSOLESREQUEST']._serialized_start=385
  _globals['_LISTCONSOLESREQUEST']._serialized_end=485
  _globals['_LISTCONSOLESRESPONSE']._serialized_start=487
  _globals['_LISTCONSOLESRESPONSE']._serialized_end=592
  _globals['_UPDATECONSOLEREQUEST']._serialized_start=594
  _globals['_UPDATECONSOLEREQUEST']._serialized_end=664
  _globals['_DELETECONSOLEREQUEST']._serialized_start=666
  _globals['_DELETECONSOLEREQUEST']._serialized_end=700
  _globals['_DELETECONSOLERESPONSE']._serialized_start=702
  _globals['_DELETECONSOLERESPONSE']._serialized_end=742
  _globals['_NINTENDOSERVICE']._serialized_start=745
  _globals['_NINTENDOSERVICE']._serialized_end=1153
# @@protoc_insertion_point(module_scope)
